Add global additional_name_servers key
nerves-networking/vintage_net pull request #281
Opened 2021-05-05 13:29 UTC by ConnorRigby

2021-05-05 14:19 UTC, fhunleth requested changes

2021-05-05 14:19 UTC, fhunleth commented on README.md
> +additional_name_servers     | List of additional DNS servers to be added to every interface
```suggestion
additional_name_servers     | List of DNS servers to be used in addition to any supplied by an interface. E.g., `[{1, 1, 1, 1}, {8, 8, 8, 8}]`
```

2021-05-05 14:19 UTC, fhunleth commented on lib/vintage_net/name_resolver.ex
> +      Keyword.get(args, :additional_name_servers, []) |> Enum.map(&IP.ip_to_tuple!/1)
I think we should log a warning and drop invalid IP addresses rather than crash. Crashes here are painful.

2021-05-05 14:56 UTC, ConnorRigby commented on lib/vintage_net/name_resolver.ex
> +      Keyword.get(args, :additional_name_servers, []) |> Enum.map(&IP.ip_to_tuple!/1)
Hm i agree actually since this would crash the entire app probably.

2021-05-06 01:19 UTC, fhunleth commented on lib/vintage_net/resolver/resolv_conf.ex
This needs cleanup, but how about:

```
name_servers = Enum.reduce(additional_name_servers, name_servers, &add_name_server("global", &1, &2))
```

2021-05-06 14:59 UTC, fhunleth approved these changes

2021-05-06 14:59 UTC, merged